
package com.mindtree.eai.programs.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.16
 * Sun Dec 17 19:57:39 IST 2017
 * Generated source version: 3.0.16
 */

@XmlRootElement(name = "getProducts", namespace = "http://programs.eai.mindtree.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProducts", namespace = "http://programs.eai.mindtree.com/")

public class GetProducts {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

