
package com.mindtree.eai.programs.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.16
 * Sun Dec 17 19:57:39 IST 2017
 * Generated source version: 3.0.16
 */

@XmlRootElement(name = "getProductCategories", namespace = "http://programs.eai.mindtree.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProductCategories", namespace = "http://programs.eai.mindtree.com/")

public class GetProductCategories {


}

